service: aws-node-project
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"
functions:
  GetEmployees:
    handler: src/handler.getEmployees
    events:
      - httpApi:
          path: /
          method: get
  PostEmployee:
    handler: src/handler.postEmployee
    events:
      - httpApi:
          path: /
          method: post
  UpdateEmployee:
    handler: handler.updateEmployee
    events:
      - httpApi:
          path: /{id}
          method: put
  DeleteEmployee:
    handler: src/handler.deleteEmployee
    events:
      - httpApi:
          path: /{id}
          method: delete
    vpc:
      securityGroupIds:
        - coloque aqui o grupo de segurança da sua vpc
      subnetIds:
        - coloque aqui o id das subnets do seu RDS